include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    # lines_longer_than_80_chars: false
    # non_constant_identifier_names: false
    # constant_identifier_names: false

analyzer:
  errors:
    argument_type_not_assignable: ignore
    invalid_assignment: ignore
  plugins:
    - dart_code_metrics
  strong-mode:
    # implicit-dynamic: true
    # implicit-casts: true
  exclude:
    # Generated code
    - "packages/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/l10n/**"
    - "lib/env/**"
    - "lib/**.graphql.dart"
    - "lib/**.gen.dart"
    - "lib/generated_plugin_registrant.dart"
    - "lib/pigeon.dart"
    # Firebase
    - "lib/src/common/constant/firebase_options.dart"
    # Localization
    - "lib/src/common/localization/intl/**"
    - "lib/src/common/localization/l10n.dart"
    # Tests
    - "test/**.mocks.dart"
    # - "test/*.dart"
    - ".test_coverage.dart"
    # Web
    - "web/**"
    # Build
    - "build/**"
    # Assets
    - "assets/**"

dart_code_metrics:
  rules:
    - prefer-single-widget-per-file:
      ignore-private-widgets: true
    # flutter 
    - always-remove-listener
    - avoid-border-all
    - avoid-returning-widgets
    - avoid-shrink-wrap-in-lists
    - avoid-unnecessary-setstate

    - avoid-wrapping-in-padding
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object
    - prefer-const-border-radius
    - prefer-correct-edge-insets-constructor
    # - prefer-extracting-callbacks
# DART
    - avoid-banned-imports
    - avoid-collection-methods-with-unrelated-types
    - avoid-duplicate-exports
    # - avoid-dynamic
    - avoid-global-state
    - avoid-ignoring-return-values
    # - avoid-late-keyword
    - avoid-missing-enum-constant-in-map
    # - avoid-nested-conditional-expressions
    # когда будешь переводить включи
    # - avoid-non-ascii-symbols
    # - avoid-non-null-assertion
    # - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    - avoid-throw-in-catch-block
    - avoid-top-level-members-in-tests
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - ban-name
    - binary-expression-operand-order
    - double-literal-format
    # - format-comment
    # - member-ordering
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    # - no-equal-arguments
    - no-equal-then-else
    # - no-magic-number
    - no-object-declaration
    - prefer-async-await
    # - prefer-commenting-analyzer-ignores
    - prefer-conditional-expressions
    # - prefer-correct-identifier-length:
    #     exceptions: ["i",'e','l','_']
    #     min-identifier-length: 2
    #     max-identifier-length: 40
    - prefer-correct-test-file-name
    - prefer-correct-type-name
    - prefer-enums-by-name
    - prefer-first
    - prefer-immediate-return
    - prefer-iterable-of
    - prefer-last
    # - prefer-match-file-name
    - prefer-moving-to-variable:
        allowed-duplicated-chains: 3
    - prefer-trailing-comma
    - prefer-trailing-comma
    - tag-name

