name: product
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # for state manager
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.0-dev.2

  # info

  device_info_plus : ^8.0.0
  package_info_plus: ^3.0.2
  path_provider: ^2.0.11
  logger: ^1.1.0
  intl: ^0.17.0-nullsafety.2
  path: ^1.8.2

  

  # helper for UI
  flash: ^2.0.5
  lottie: ^2.0.0
  # google_fonts: ^3.0.1
  flutter_native_splash: ^2.2.15

  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.6.0
  flex_color_scheme: ^6.1.1
  introduction_screen: ^3.1.0


  # modal_bottom_sheet: ^2.1.2
  #  for TEST
  device_preview: ^1.1.0
  feedback: ^2.5.0
  dio_log: ^2.0.4

 
  # Key-value local cache/db
  shared_preferences: ^2.0.15
  hydrated_bloc: ^9.0.0
  # validation
  formz: ^0.4.1
  mask_text_input_formatter: ^2.4.0
  crypto: ^3.0.2


  #  Network
  dio: ^4.0.6
  connectivity_plus: ^3.0.2
  # http: ^0.13.5

  #   for navigation
  go_router: ^5.2.0
  
  # for models
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4

  # sprintf: ^7.0.0

 # firebase
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_remote_config: ^3.0.6
  firebase_messaging: ^14.1.1
  cloud_firestore: ^4.1.0
  firebase_in_app_messaging: ^0.7.0+6
  cloud_functions: ^4.0.5
  firebase_analytics: ^10.0.6


  # native calls
  syncfusion_flutter_pdfviewer: ^20.3.58
  url_launcher: ^6.1.7
  share_plus: ^6.3.0



  # ******************************
  #  local packages
  # ******************************
  dadata:
    path: packages/dadata
 


  drift: ^2.3.0
  sqlite3_flutter_libs: ^0.5.12


  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # help lint
  dart_code_metrics: ^5.0.1
  very_good_analysis: ^3.1.0

  # helpers UI
  flutter_launcher_icons:
    ^0.11.0

    # for models
  freezed: ^2.2.1
  build_runner: ^2.3.2

  drift_dev: ^2.3.2

  


flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/svg/
    - assets/lottie/




# ******************************
# flutter pub run flutter_launcher_icons:main
flutter_icons:
 ios: true
 android: false
 remove_alpha_ios: true
 image_path: "assets/image/icon.png"

# flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  android: true
  ios: true
  web: true
  desktop: false
  color: "#ffffff"
  image: assets/image/logo.png
  android_12:
