// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'address_tooltip_m.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_AddressTooltip _$$_AddressTooltipFromJson(Map<String, dynamic> json) =>
    _$_AddressTooltip(
      (json['suggestions'] as List<dynamic>)
          .map((e) => SuggestionsAddress.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$$_AddressTooltipToJson(_$_AddressTooltip instance) =>
    <String, dynamic>{
      'suggestions': instance.suggestions.map((e) => e.toJson()).toList(),
    };

_$_SuggestionsAddress _$$_SuggestionsAddressFromJson(
        Map<String, dynamic> json) =>
    _$_SuggestionsAddress(
      value: json['value'] as String? ?? '',
      unrestricted_value: json['unrestricted_value'] as String? ?? '',
      data: json['data'] == null
          ? const DataAddress()
          : DataAddress.fromJson(json['data'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$$_SuggestionsAddressToJson(
        _$_SuggestionsAddress instance) =>
    <String, dynamic>{
      'value': instance.value,
      'unrestricted_value': instance.unrestricted_value,
      'data': instance.data.toJson(),
    };

_$_DataAddress _$$_DataAddressFromJson(Map<String, dynamic> json) =>
    _$_DataAddress(
      postal_code: json['postal_code'] as String? ?? '',
      country: json['country'] as String? ?? '',
      country_iso_code: json['country_iso_code'] as String? ?? '',
      federal_district: json['federal_district'] as String? ?? '',
      region_fias_id: json['region_fias_id'] as String? ?? '',
      region_kladr_id: json['region_kladr_id'] as String? ?? '',
      region_iso_code: json['region_iso_code'] as String? ?? '',
      region_with_type: json['region_with_type'] as String? ?? '',
      region_type: json['region_type'] as String? ?? '',
      region_type_full: json['region_type_full'] as String? ?? '',
      region: json['region'] as String? ?? '',
      area_fias_id: json['area_fias_id'] as String? ?? '',
      area_kladr_id: json['area_kladr_id'] as String? ?? '',
      area_with_type: json['area_with_type'] as String? ?? '',
      area_type: json['area_type'] as String? ?? '',
      area_type_full: json['area_type_full'] as String? ?? '',
      area: json['area'] as String? ?? '',
      city_fias_id: json['city_fias_id'] as String? ?? '',
      city_kladr_id: json['city_kladr_id'] as String? ?? '',
      city_with_type: json['city_with_type'] as String? ?? '',
      city_type: json['city_type'] as String? ?? '',
      city_type_full: json['city_type_full'] as String? ?? '',
      city: json['city'] as String? ?? '',
      city_area: json['city_area'] as String? ?? '',
      city_district_fias_id: json['city_district_fias_id'] as String? ?? '',
      city_district_kladr_id: json['city_district_kladr_id'] as String? ?? '',
      city_district_with_type: json['city_district_with_type'] as String? ?? '',
      city_district_type: json['city_district_type'] as String? ?? '',
      city_district_type_full: json['city_district_type_full'] as String? ?? '',
      city_district: json['city_district'] as String? ?? '',
      settlement_fias_id: json['settlement_fias_id'] as String? ?? '',
      settlement_kladr_id: json['settlement_kladr_id'] as String? ?? '',
      settlement_with_type: json['settlement_with_type'] as String? ?? '',
      settlement_type: json['settlement_type'] as String? ?? '',
      settlement_type_full: json['settlement_type_full'] as String? ?? '',
      settlement: json['settlement'] as String? ?? '',
      street_fias_id: json['street_fias_id'] as String? ?? '',
      street_kladr_id: json['street_kladr_id'] as String? ?? '',
      street_with_type: json['street_with_type'] as String? ?? '',
      street_type: json['street_type'] as String? ?? '',
      street_type_full: json['street_type_full'] as String? ?? '',
      street: json['street'] as String? ?? '',
      stead_fias_id: json['stead_fias_id'] as String? ?? '',
      stead_cadnum: json['stead_cadnum'] as String? ?? '',
      stead_type: json['stead_type'] as String? ?? '',
      stead_type_full: json['stead_type_full'] as String? ?? '',
      stead: json['stead'] as String? ?? '',
      house_fias_id: json['house_fias_id'] as String? ?? '',
      house_kladr_id: json['house_kladr_id'] as String? ?? '',
      house_cadnum: json['house_cadnum'] as String? ?? '',
      house_type: json['house_type'] as String? ?? '',
      house_type_full: json['house_type_full'] as String? ?? '',
      house: json['house'] as String? ?? '',
      block_type: json['block_type'] as String? ?? '',
      block_type_full: json['block_type_full'] as String? ?? '',
      block: json['block'] as String? ?? '',
      entrance: json['entrance'] as String? ?? '',
      floor: json['floor'] as String? ?? '',
      flat_fias_id: json['flat_fias_id'] as String? ?? '',
      flat_cadnum: json['flat_cadnum'] as String? ?? '',
      flat_type: json['flat_type'] as String? ?? '',
      flat_type_full: json['flat_type_full'] as String? ?? '',
      flat: json['flat'] as String? ?? '',
      flat_area: json['flat_area'] as String? ?? '',
      square_meter_price: json['square_meter_price'] as String? ?? '',
      flat_price: json['flat_price'] as String? ?? '',
      postal_box: json['postal_box'] as String? ?? '',
      fias_id: json['fias_id'] as String? ?? '',
      fias_code: json['fias_code'] as String? ?? '',
      fias_level: json['fias_level'] as String? ?? '',
      fias_actuality_state: json['fias_actuality_state'] as String? ?? '',
      kladr_id: json['kladr_id'] as String? ?? '',
      geoname_id: json['geoname_id'] as String? ?? '',
      capital_marker: json['capital_marker'] as String? ?? '',
      okato: json['okato'] as String? ?? '',
      oktmo: json['oktmo'] as String? ?? '',
      tax_office: json['tax_office'] as String? ?? '',
      tax_office_legal: json['tax_office_legal'] as String? ?? '',
      timezone: json['timezone'] as String? ?? '',
      geo_lat: json['geo_lat'] as String? ?? '',
      geo_lon: json['geo_lon'] as String? ?? '',
      beltway_hit: json['beltway_hit'] as String? ?? '',
      beltway_distance: json['beltway_distance'] as String? ?? '',
      metro:
          (json['metro'] as List<dynamic>?)?.map((e) => e as String).toList() ??
              const [],
      divisions: json['divisions'] as String? ?? '',
      qc_geo: json['qc_geo'] as String? ?? '',
      qc_complete: json['qc_complete'] as String? ?? '',
      qc_house: json['qc_house'] as String? ?? '',
      history_values: (json['history_values'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          const [],
      unparsed_parts: json['unparsed_parts'] as String? ?? '',
      source: json['source'] as String? ?? '',
      qc: json['qc'] as String? ?? '',
    );

Map<String, dynamic> _$$_DataAddressToJson(_$_DataAddress instance) =>
    <String, dynamic>{
      'postal_code': instance.postal_code,
      'country': instance.country,
      'country_iso_code': instance.country_iso_code,
      'federal_district': instance.federal_district,
      'region_fias_id': instance.region_fias_id,
      'region_kladr_id': instance.region_kladr_id,
      'region_iso_code': instance.region_iso_code,
      'region_with_type': instance.region_with_type,
      'region_type': instance.region_type,
      'region_type_full': instance.region_type_full,
      'region': instance.region,
      'area_fias_id': instance.area_fias_id,
      'area_kladr_id': instance.area_kladr_id,
      'area_with_type': instance.area_with_type,
      'area_type': instance.area_type,
      'area_type_full': instance.area_type_full,
      'area': instance.area,
      'city_fias_id': instance.city_fias_id,
      'city_kladr_id': instance.city_kladr_id,
      'city_with_type': instance.city_with_type,
      'city_type': instance.city_type,
      'city_type_full': instance.city_type_full,
      'city': instance.city,
      'city_area': instance.city_area,
      'city_district_fias_id': instance.city_district_fias_id,
      'city_district_kladr_id': instance.city_district_kladr_id,
      'city_district_with_type': instance.city_district_with_type,
      'city_district_type': instance.city_district_type,
      'city_district_type_full': instance.city_district_type_full,
      'city_district': instance.city_district,
      'settlement_fias_id': instance.settlement_fias_id,
      'settlement_kladr_id': instance.settlement_kladr_id,
      'settlement_with_type': instance.settlement_with_type,
      'settlement_type': instance.settlement_type,
      'settlement_type_full': instance.settlement_type_full,
      'settlement': instance.settlement,
      'street_fias_id': instance.street_fias_id,
      'street_kladr_id': instance.street_kladr_id,
      'street_with_type': instance.street_with_type,
      'street_type': instance.street_type,
      'street_type_full': instance.street_type_full,
      'street': instance.street,
      'stead_fias_id': instance.stead_fias_id,
      'stead_cadnum': instance.stead_cadnum,
      'stead_type': instance.stead_type,
      'stead_type_full': instance.stead_type_full,
      'stead': instance.stead,
      'house_fias_id': instance.house_fias_id,
      'house_kladr_id': instance.house_kladr_id,
      'house_cadnum': instance.house_cadnum,
      'house_type': instance.house_type,
      'house_type_full': instance.house_type_full,
      'house': instance.house,
      'block_type': instance.block_type,
      'block_type_full': instance.block_type_full,
      'block': instance.block,
      'entrance': instance.entrance,
      'floor': instance.floor,
      'flat_fias_id': instance.flat_fias_id,
      'flat_cadnum': instance.flat_cadnum,
      'flat_type': instance.flat_type,
      'flat_type_full': instance.flat_type_full,
      'flat': instance.flat,
      'flat_area': instance.flat_area,
      'square_meter_price': instance.square_meter_price,
      'flat_price': instance.flat_price,
      'postal_box': instance.postal_box,
      'fias_id': instance.fias_id,
      'fias_code': instance.fias_code,
      'fias_level': instance.fias_level,
      'fias_actuality_state': instance.fias_actuality_state,
      'kladr_id': instance.kladr_id,
      'geoname_id': instance.geoname_id,
      'capital_marker': instance.capital_marker,
      'okato': instance.okato,
      'oktmo': instance.oktmo,
      'tax_office': instance.tax_office,
      'tax_office_legal': instance.tax_office_legal,
      'timezone': instance.timezone,
      'geo_lat': instance.geo_lat,
      'geo_lon': instance.geo_lon,
      'beltway_hit': instance.beltway_hit,
      'beltway_distance': instance.beltway_distance,
      'metro': instance.metro,
      'divisions': instance.divisions,
      'qc_geo': instance.qc_geo,
      'qc_complete': instance.qc_complete,
      'qc_house': instance.qc_house,
      'history_values': instance.history_values,
      'unparsed_parts': instance.unparsed_parts,
      'source': instance.source,
      'qc': instance.qc,
    };
