// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkjAz2FOw2CIS7xkaKbqT7nVGeE_PgSWU',
    appId: '1:369496255108:web:30698851ca85c6e1c5b0d1',
    messagingSenderId: '369496255108',
    projectId: 'product-13769',
    authDomain: 'product-13769.firebaseapp.com',
    databaseURL: 'https://product-13769-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'product-13769.appspot.com',
    measurementId: 'G-WYPF058V2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-HwoYjl2vuVYbXqo1ep23tE3gOEqLs4I',
    appId: '1:369496255108:android:8ee0fcaf5064fce4c5b0d1',
    messagingSenderId: '369496255108',
    projectId: 'product-13769',
    databaseURL: 'https://product-13769-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'product-13769.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_dI8FnG7kSlzsRpRHhoyDRkt9aQEnVWQ',
    appId: '1:369496255108:ios:ed3804e74b42c25cc5b0d1',
    messagingSenderId: '369496255108',
    projectId: 'product-13769',
    databaseURL: 'https://product-13769-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'product-13769.appspot.com',
    iosClientId: '369496255108-mb9e9paf7sg9ah1nkd0mq15olhokm02l.apps.googleusercontent.com',
    iosBundleId: 'a.dev.mobile.product',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_dI8FnG7kSlzsRpRHhoyDRkt9aQEnVWQ',
    appId: '1:369496255108:ios:ed3804e74b42c25cc5b0d1',
    messagingSenderId: '369496255108',
    projectId: 'product-13769',
    databaseURL: 'https://product-13769-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'product-13769.appspot.com',
    iosClientId: '369496255108-mb9e9paf7sg9ah1nkd0mq15olhokm02l.apps.googleusercontent.com',
    iosBundleId: 'a.dev.mobile.product',
  );
}
