name: "Build android"
on:
  push:
    branches: 
      - develop
      - 'release/**'
  pull_request:
    branches: 
      - develop
      - master
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Run flutter doctor
        run: flutter doctor -v
        
      - name: Checkout code        
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.18.5      
      - name: Get dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - run: flutter build apk


