name: "Build android"
on:
  push:
    branches:
      - develop
      - "release/**"
  pull_request:
    branches:
      - develop
      - master
jobs:
  build_apk:
    name: Build Flutter (Android)
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - uses: dart-lang/setup-dart@v1.3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable" # or: 'beta', 'dev' or 'master'

      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
      
  beta_apk:
    name: Upload Android Beta to Firebase App Distribution
    needs: [build_apk]
    runs-on: ubuntu-latest
    steps:
      - uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: /github/workspace/build/app/outputs/flutter-apk/app-release.apk


# name: Deploy Android to Firebase App Distribution on merge
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: "stable"

#       - name: Install Dependencies
#         run: flutter packages get

#       - name: Decode Keystore
#         id: write_file
#         uses: timheuer/base64-to-file@v1
#         with:
#           fileName: "key.jks"
#           encodedString: ${{ secrets.KEYSTORE }}

#       - name: Build
#         run: flutter build apk
#         env:
#           ANDROID_KEYSTORE_PATH: ${{ steps.write_file.outputs.filePath }}
#           ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
#           ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
#           ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

#       - name: Firebase App Distribution
#         uses: wzieba/Firebase-Distribution-Github-Action@v1
#         with:
#           appId: ${{secrets.FIREBASE_APP_ID}}
#           serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
#           groups: testers
#           file: /github/workspace/build/app/outputs/flutter-apk/app-release.apk