name: "Build android"
on:
  push:
    branches: 
      - develop
      - 'release/**'
  pull_request:
    branches: 
      - develop
      - master
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
       
      - name: Checkout code   
        uses: actions/checkout@v2
      # - uses: dart-lang/setup-dart@v1.3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
          
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk


